[package]
name = "kehadiran-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.13.1"
pdf-extract = "0.6.5"
serde = "1.0.163"
serde_json = "1.0.96"
